apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tenants.multi-saas-crm.grg-automation.com
spec:
  group: multi-saas-crm.grg-automation.com
  names:
    kind: Tenant
    plural: tenants
    singular: tenant
    shortNames:
      - tn
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                organizationName:
                  type: string
                tier:
                  type: string
                  enum: [starter, professional, enterprise]
                resources:
                  type: object
                  properties:
                    cpu:
                      type: object
                      properties:
                        request:
                          type: string
                        limit:
                          type: string
                    memory:
                      type: object
                      properties:
                        request:
                          type: string
                        limit:
                          type: string
                    storage:
                      type: object
                      properties:
                        size:
                          type: string
                        storageClass:
                          type: string
                services:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      version:
                        type: string
                      replicas:
                        type: integer
                      env:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                      config:
                        type: object
                        additionalProperties:
                          type: string
                database:
                  type: object
                  properties:
                    type:
                      type: string
                      enum: [postgres, mysql]
                    version:
                      type: string
                    poolSize:
                      type: integer
                    backup:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                        schedule:
                          type: string
                        retentionDays:
                          type: integer
                domains:
                  type: array
                  items:
                    type: string
                features:
                  type: object
                  additionalProperties:
                    type: boolean
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum: [Pending, Provisioning, Active, Failed, Terminating]
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                services:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      ready:
                        type: boolean
                      replicas:
                        type: integer
                      version:
                        type: string
                      endpoints:
                        type: array
                        items:
                          type: string
                      lastUpdated:
                        type: string
                databaseStatus:
                  type: object
                  properties:
                    ready:
                      type: boolean
                    connectionUrl:
                      type: string
                    migrationsRun:
                      type: boolean
                    lastBackupTime:
                      type: string
                resourceMetrics:
                  type: object
                  properties:
                    cpuUsage:
                      type: string
                    memoryUsage:
                      type: string
                    storageUsage:
                      type: string
                    updatedAt:
                      type: string
                lastReconciled:
                  type: string
                url:
                  type: string
